import useTranslation from "next-translate/useTranslation";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  const { t, lang } = useTranslation("common");
  //eslint-disable-next-line
  console.log(t, lang);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{t("title")}</h1>
        <p>{t("description")}</p>
        <Link href="/home" locale="en">
          <h2>Anglais</h2>
        </Link>
        <Link href="/inicio" locale="es">
          <h2>Français</h2>
        </Link>
      </main>
    </div>
  );
}

export async function getStaticPaths() {
  const rutas = ["/es/incio", "/en/home"];
  const paths = rutas.map((item) => {
    const ruta = item.split("/");
    const locale = ruta.shift();
    return { params: { uri: ruta }, locale };
  });

  return {
    paths: paths || [],
    fallback: false
  };
}
